define({
	SCREEN_WIDTH : window.innerWidth,
	SCREEN_HEIGHT : window.innerHeight,

	CURRENT_TIMING : 0.0, // Gameloop time since execution
	LEAP_FRAME : null,

	STARS_NB : 50,

	PLAYER_SPEED_X : 7,
	PLAYER_SPEED_Y : 5,
	JUMP_MAX_HEIGHT : 20,
	GRAVITY : .8,

	BULLET_SPEED : 20,
	SHOTS_INTERVAL : 200,
	MACHINEGUN_INTERVAL : 500,
	ARMAGEDDON_SPEED : 5,
	ARMAGEDDON_FIREBALL_WIDTH : 128,
	ARMAGEDDON_FIREBALL_HEIGHT : 128,
	ARMAGEDDON_FIRE_DELAY : 1000,

	BONUS_INTERVAL : 25000,
	BONUS_LIFE_GAIN : 15,
	BONUS_MISSILE_DELAY : 10000,

	// Asteroids
	OBSTACLE_SPEED_MIN_ASTEROID : 2,
	OBSTACLE_SPEED_MAX_ASTEROID : 4,
	OBSTACLE_SPEED_ROTATION_MIN_ASTEROID : .001,
	OBSTACLE_SPEED_ROTATION_MAX_ASTEROID : .01,
	// Soldats
	OBSTACLE_SPEED_MIN_SOLDAT : 2,
	OBSTACLE_SPEED_MAX_SOLDAT : 4,
	OBSTACLE_SPEED_ROTATION_MIN_SOLDAT : .01,
	OBSTACLE_SPEED_ROTATION_MAX_SOLDAT : .1,
	// Fighters
	OBSTACLE_SPEED_MIN_FIGHTER : 3,
	OBSTACLE_SPEED_MAX_FIGHTER : 6,
	OBSTACLE_SPEED_ROTATION_MIN_FIGHTER : 0,
	OBSTACLE_SPEED_ROTATION_MAX_FIGHTER : 0,

	OBSTACLE_INTERVAL_ASTEROID : 1000,
	OBSTACLE_INTERVAL_SOLDAT : 3000,
	OBSTACLE_INTERVAL_FIGHTER : 7000,
	OBSTACLE_INTERVAL_BOSS : 60000,
	OBSTACLE_DAMAGE : 5,

	SCORE_GAIN_ASTEROID : 500,
	SCORE_GAIN_SOLDAT : 1000,
	SCORE_GAIN_FIGHTER : 2000,

	BONUS_MAX_TIMING : 5000 // 5 seconds max for bonuses staying at screen
});